// Lazy + cached translation of order DATA (product names, notes, address) for
// display in the chosen app language.
//
// Model:
//  - order.lang        = language the BASE fields are written in ('en' default).
//                        New orders are extracted directly in the app language and
//                        tagged accordingly, so they need no extra translation.
//  - order.translations = { [lang]: { products: [name,...], notes, address } }
//                        cache filled on demand and persisted with the order.
//
// Not translated: customerName, phone, orderId, numeric amounts/quantities.

import { translateTexts } from '../api/geminiApi';

// Bump when translation quality/logic changes — invalidates older cached
// translations so they get regenerated by the improved backend.
const TV = 3;

function baseLangOf(order) {
  return (order && order.lang) || 'en';
}

// Orders are stored with a stable base (English from extraction) and translated
// for display via the validated /api/translate. Older builds tagged orders with
// the target language directly (sometimes producing the wrong script), so reset
// any non-English tag back to 'en' to force a clean re-translation.
export function migrateOrders(orders) {
  if (!orders || !orders.length) return { orders, changed: false };
  let changed = false;
  const next = orders.map(o => {
    if (o && o.lang && o.lang !== 'en') {
      changed = true;
      return { ...o, lang: 'en' };
    }
    return o;
  });
  return { orders: changed ? next : orders, changed };
}

// Returns an order whose display fields are in `lang`, using the cache when
// available and otherwise falling back to the base (untranslated) fields.
export function getOrderDisplay(order, lang) {
  if (!order) return order;
  if (!lang || lang === baseLangOf(order)) return order;
  const cached = order.translations && order.translations[lang];
  if (!cached || cached._tv !== TV) return order; // fallback to base until (re)translated
  const baseProducts = order.products || [];
  const names = Array.isArray(cached.products) ? cached.products : [];
  return {
    ...order,
    products: baseProducts.map((p, i) => ({
      ...p,
      name: names[i] != null ? names[i] : p.name,
    })),
    notes: cached.notes != null ? cached.notes : order.notes,
    address: cached.address != null ? cached.address : order.address,
  };
}

export function orderNeedsTranslation(order, lang) {
  if (!order || !lang) return false;
  if (lang === baseLangOf(order)) return false;
  const cached = order.translations && order.translations[lang];
  return !(cached && cached._tv === TV);
}

// Build the flat list of translatable strings for one order + a descriptor to
// reassemble them afterwards.
function collectOrderTexts(order) {
  const productNames = (order.products || []).map(p => (p && p.name) || '');
  const hasNotes = !!order.notes;
  const hasAddress = !!order.address;
  const texts = [...productNames];
  if (hasNotes) texts.push(order.notes);
  if (hasAddress) texts.push(order.address);
  return { texts, productCount: productNames.length, hasNotes, hasAddress };
}

function applyTranslated(order, lang, translatedSlice, desc) {
  const products = translatedSlice.slice(0, desc.productCount);
  let idx = desc.productCount;
  const notes = desc.hasNotes ? translatedSlice[idx++] : order.notes;
  const address = desc.hasAddress ? translatedSlice[idx++] : order.address;
  return {
    ...order,
    translations: {
      ...(order.translations || {}),
      [lang]: { products, notes, address, _tv: TV },
    },
  };
}

// Translate up to `limit` untranslated orders into `lang` in a SINGLE batched
// backend call. Returns { orders: newArray, changed: bool }. Orders already in
// `lang` or already cached are returned untouched.
export async function translateOrders(orders, lang, token, options = {}) {
  const limit = options.limit || 25;
  if (!orders || !orders.length || !lang || lang === 'en') {
    return { orders, changed: false };
  }

  // Pick the targets (preserve their indices in the original array).
  const targets = [];
  for (let i = 0; i < orders.length && targets.length < limit; i++) {
    if (orderNeedsTranslation(orders[i], lang)) {
      targets.push({ index: i, desc: collectOrderTexts(orders[i]) });
    }
  }
  if (!targets.length) return { orders, changed: false };

  // Flatten all texts into one request, remembering per-target offsets.
  const allTexts = [];
  targets.forEach(tgt => {
    tgt.offset = allTexts.length;
    allTexts.push(...tgt.desc.texts);
  });

  // Nothing actually translatable (e.g. orders with no products/notes/address):
  // still mark them cached so we don't retry every render.
  let translated = allTexts;
  if (allTexts.length > 0) {
    translated = await translateTexts(allTexts, lang, token);
  }

  const next = orders.slice();
  targets.forEach(tgt => {
    const slice = translated.slice(
      tgt.offset,
      tgt.offset + tgt.desc.texts.length,
    );
    next[tgt.index] = applyTranslated(orders[tgt.index], lang, slice, tgt.desc);
  });
  return { orders: next, changed: true };
}

export { translateTexts };
